### PR TITLE
Add Linux instructions to Readme

### PR DESCRIPTION
**Pull request by riQQ**
Ref #32

### CODE REVIEW

**Comment by bstaple1** [comment]
Hi riQQ, thanks for confirming that the app works on Linux! I like the changes you made to the README. However, I think it would be a good idea if we added a section or step where we mention exactly where Linux users can locate the player log. What do you think?

**Comment by riQQ** [comment]
Sure, but that depends on how they setup Wine. I can give example / default locations for Bottles and Lutris. Anything you would like to add?

**Comment by bstaple1** [comment]
I added an additional step (step 8) to the python run steps section. Could you fill out the Bottles and Lutris portions of that step? Thanks.

**Comment by riQQ** [comment]
Done

**Pull request merged**
